---
root: true # Disables inheritance from parent config.
env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:unicorn/recommended
  - plugin:jsx-a11y/recommended
  - plugin:cypress/recommended
  - plugin:prettier/recommended
settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
    # Uses `eslint-import-resolver-typescript` to support the `exports` syntax in `package.json`
    # @see https://github.com/import-js/eslint-import-resolver-typescript
    typescript:
      alwaysTryTypes: true
rules:
  # The Unicorn plugin comes with opinionated checks, including some that we prefer disabling.
  'unicorn/no-array-for-each':
    # Performance is no longer an issue - we prefer `forEach` for readability.
    - off
  'unicorn/numeric-separators-style':
    # Doesn't add a lot of value and makes numbers look odd.
    - off
  'unicorn/prefer-type-error':
    # Not really applicable when using TypeScript (mostly triggers false positives).
    - off
  # Increase the level to 'error' for unused variables (the default is set to 'warning')
  # @see https://typescript-eslint.io/rules/no-unused-vars/
  '@typescript-eslint/no-unused-vars':
    - error
    - args: all
  # This check will only be enabled for TypeScript (the real configuration is in the 'overrides')
  # @see https://typescript-eslint.io/rules/explicit-function-return-type/#configuring-in-a-mixed-jsts-codebase
  '@typescript-eslint/explicit-function-return-type': 'off'
overrides:
  # Disable abbreviation check on Cypress' `e2e` file.
  - files:
      - 'cypress/support/*'
    rules:
      'unicorn/prevent-abbreviations':
        - error
        - ignore:
            - '^e2e$'
  # The acronyms `props` is too common in React to avoid using it.
  - files:
      - 'src/**/*'
    rules:
      'unicorn/prevent-abbreviations':
        - error
        - ignore:
            - 'props'
            - 'Props'
  # TypeScript configurations
  - files:
      - '*.ts'
      - '*.mts'
      - '*.cts'
      - '*.tsx'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project:
        - 'tsconfig.json'
        - 'cypress/tsconfig.json'
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    rules:
      # Show errors when missing return types are missing on relevant functions
      '@typescript-eslint/explicit-function-return-type':
        - error
        - allowExpressions: true
          allowConciseArrowFunctionExpressionsStartingWithVoid: true
